alchemy-run/alchemy

- README.md
The getting started script had an incorrect field, and a missing required field
> chore: Update getting started

- alchemy-web/.vitepress/config.mts
- alchemy-web/docs/providers/cloudflare/assets.md
- alchemy/src/cloudflare/assets.ts
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/r2-rest-state-store.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/test/cloudflare/worker.test.ts
```ts
const assets = await Assets("static-assets", {
path: "./dist",
});
const worker = await Worker("my-static-site", {
name: "my-static-site",
entrypoint: "./index.ts",
bindings: {
ASSETS: assets,
},
});
```
Now you can apply Cloudflare's pattern for efficiently serving assets from the cache
```ts
export default {
async fetch(request, env, ctx) {
const url = new URL(request.url);
if (url.pathname.startsWith("/api/")) {
return new Response("Worker with assets is running!", { 
status: 200,
headers: { 'Content-Type': 'text/plain' }
});
}
try {
return env.ASSETS.fetch(request);
} catch (err) {
console.log(err);
return new Response(\`\${err}\`, { status: 404 });
}
}
};
```
> feat: Assets resource & Worker Binding

- alchemy-web/docs/guides/cloudflare-vitejs.md
- alchemy/src/apply.ts
- alchemy/src/cloudflare/bucket.ts
- alchemy/test/cloudflare/bucket.test.ts
There was a bug where the `R2Bucket` resources would instantiate a R2 client during create, update and delete phases even though it was only needed to empty the R2 bucket during delete phase.
This caused a problem where a bucket couldn't even be created without first creating and storing R2_ACCESS_KEY and R2_SECRET_KEY in your .env
Also, it's dangerous behavior to delete objects by default, so I've changed the behavior to be opt-in instead of opt-out.
> fix: opt-in to empty R2 bucket and document CF credentials in Guide

- alchemy/src/index.ts
I tried using the cursorrules to generate a Resource and in order to create a test, it wants to use Scope, but that's not exported yet.
I assume we only want to export the type, since scope is constructed internally.
Sample generated in my codebase:
```ts
import "alchemy/test/bun";
import { describe, expect } from "bun:test";
import alchemy, { type Scope } from "alchemy";
import { TypeDBServer } from "../../src/typedb/server";
import { Socket } from "net";
describe("TypeDBServer Resource", () => {
const testId = `test-typedb-server`;
alchemy.test(import.meta)("create, verify connection, and destroy server", async (scope: Scope) => {
let server: TypeDBServer | undefined;
try {
// Create a test server
server = await TypeDBServer(testId, {
binaryPath: process.env.TYPEDB_BINARY_PATH || …
```
> fix: export type Scope

- alchemy/src/cloudflare/api.ts
- alchemy/src/cloudflare/worker.ts
- bun.lock
I saw some network errors when uploading assets. Fixing by adding exponential retries for all Cloudflare API calls when a transient connection reset error occurs.
> fix: retry transient network failures in cloudflare API

- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/bucket.ts
- alchemy/src/cloudflare/d1-database.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/pipeline.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/test/cloudflare/d1-database.test.ts
- alchemy/test/cloudflare/pipeline.test.ts
```ts
const bucket = await R2Bucket("worker-bucket", {
name: "my-bucket",
});
// Create a pipeline with the R2 bucket as destination
const pipeline = await Pipeline<{ name: string; age: number }>(
"worker-pipeline",
{
name: "worker-pipeline",
source: [
{
type: "binding",
format: "json",
},
],
destination: {
type: "r2",
format: "json",
path: {
bucket: bucket.name,
prefix: "worker-logs",
},
credentials: {
accessKeyId: alchemy.secret(process.env.R2_ACCESS_KEY_ID!),
secretAccessKey: alchemy.secret(process.env.R2_SECRET_ACCESS_KEY!),
},
batch: {
maxMb: 1,
maxSeconds: 1,
maxRows: 100,
},
},
}
);
export const website = await Worker("worker", {
name: "alchemy-example-vite-api",
bindings: {
PIPELINE: pipeline,
},
});
import { env } from "cloudflare:workers";
env.PIPELINE.send();
```
> feat: cloudflare pipelines and bindings

- alchemy/src/cloudflare/wrangler.json.ts
I noticed that when binding a D1 Database, it was not properly exported to the wrangler.json
> Add d1_databases to wrangler.json

- alchemy/src/esbuild/bundle.ts
This pr to fix the bundle to allow for output to mjs and support of main outdir/outfile esbuild params. 
- Remove creating a magic "dist" if none is provided, throw if neither a outdir or outfile is passed, if both are passed, esbuild will correctly bark at you. 
Tested with the following options: 
```
const bundle = await Bundle("example-bundle", {
entryPoint: "./src/index.mts",
outdir: "./dist",
format: "esm",
platform: "node",
target: "node20",
external: ["@aws-sdk/*"],
options: {
outExtension: { ".js": ".mjs" },
},
});
```
```
const bundle = await Bundle("example-bundle", {
entryPoint: "./src/index.mts",
outfile: "./dist/index.mjs",
format: "esm",
platform: "node",
target: "node20",
external: ["@aws-sdk/*"]
});
```
> removed hard-coded references

- alchemy/src/cloudflare/bound.ts
This fixes the type resolution of environment variables added to the bindings of a worker
> fix(cloudflare): add string resolution in bound.ts

- alchemy/src/aws/function.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/esbuild/bundle.ts
- alchemy/test/aws/function.test.ts
- alchemy/test/cloudflare/worker.test.ts
- alchemy/test/esbuild.test.ts
- examples/aws-app/alchemy.run.ts
There was a regression where the `Bundle` resource required a `outfile` or `outdir`. This change makes it so the `Bundle` can operate entirely in memory and now returns the bundle content which is then used in `Function` and `Worker`.
I also updated `Function` to accept `bundle: Bundle` instead of `zipPath: string` since `zipPath` was not doing what it was meant to do (actually upload a path to a zip file, instead it zipped up a `.js` file)
BREAKING CHANGE:
```ts
const bundle = await Bundle(.);
await Function("my-func", {
// zipPath is not longer supported, pass bundle instead
bundle
});
```
> fix: in-memory bundle and update aws/Function to accept bundle instead of zipPath

- alchemy/src/cloudflare/d1-database.ts
- alchemy/src/cloudflare/wrangler.json.ts
The migrationsDir was not exported in the wrangler.json which in turns prevented the D1 migrations to be applied locally for instance.
> fix(cloudflare): add `migrations_dir` in wrangler.json

- alchemy/src/cloudflare/bucket.ts
- alchemy/src/cloudflare/r2-rest-state-store.ts
- alchemy/test/cloudflare/bucket.test.ts
- alchemy/test/cloudflare/r2-rest-state-store.test.ts
Fixes #100 
I don't have `R2_*` tokens setup yet, but looking good...
```console
bun test v1.0.29 (a146856d)
alchemy/test/cloudflare/bucket.test.ts:
Create:  "eric/eric-bucket.test.ts/create, update, and delete bucket/eric-test-bucket"
Created: "eric/eric-bucket.test.ts/create, update, and delete bucket/eric-test-bucket"
Update:  "eric/eric-bucket.test.ts/create, update, and delete bucket/eric-test-bucket"
Updated: "eric/eric-bucket.test.ts/create, update, and delete bucket/eric-test-bucket"
Delete:  "eric/eric-bucket.test.ts/create, update, and delete bucket/eric-test-bucket"
Deleted: "eric/eric-bucket.test.ts/create, update, and delete bucket/eric-test-bucket"
✓ R2 Bucket Resource > create, update, and delete bucket [5160.41ms]
Create:  "eric/eric-bucket.test.ts/bucket with …
```
> feat(cloudflare): default R2RestStateStore bucketName to alchemy-state

- alchemy-web/.vitepress/config.mts
- alchemy-web/.vitepress/theme/index.ts
- alchemy-web/docs/getting-started.md
- alchemy-web/package.json
I'm a `pnpm` user primarily, and this also started showing places that `bun`'s built-in `.ts` support has slight differences from others.
This is the start for updating other parts of the docs to have per-package-manager code blocks...
> chore(docs): add vitepress-plugin-group-icons for ::: code-block

- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/test/cloudflare/wrangler-json.test.ts
**EDIT**
Opted to move the `wrangler.jsonc` generation into user-code.  There's benefit to move `processBindings` out for re-use in user-land, but I feel like this is in _niche_ territory.
--- 
_Previous motivation below..._
Users can use Alchemy for creating Resources (e.g. `R2Bucket`, etc.) that can be used for generating a dynamic `wrangler.jsonc` using these Resources' IDs.
However, today `WranglerJson` requires a `worker`.
In my real-world application, this adds **22 seconds** to Alchemy's deploy time (otherwise < 1 second)!
This PR makes `worker` optional so users can generate a dynamic `wrangler.jsonc` and run `wrangler dev|deploy` as normal, but with IaC resources (e.g. `binding`)
> WranglerJson returns `spec` for re-use

- alchemy/src/alchemy.ts
- alchemy/src/apply.ts
- alchemy/src/cloudflare/queue.ts
- alchemy/src/cloudflare/r2-rest-state-store.ts
- alchemy/src/context.ts
- alchemy/src/destroy.ts
- alchemy/src/fs/file-system-state-store.ts
- alchemy/src/resource.ts
- alchemy/src/scope.ts
- alchemy/src/state.ts
We currently store properties like `ID`, `Scope`, `Kind` on the Resource's Output which can conflict with user-defined properties.
Usually we don't conflict because most properties are lower-case, but this is not always true - e.g. for the Control API https://github.com/sam-goodwin/alchemy/pull/132
Instead, now that `serde.ts` can serialize symbols, we move these to unique symbols to ensure they are totally isolated.
State is auto-migrated to the new format:
> fix: move core Resource properties to Symbols

- alchemy-web/docs/providers/os/exec.md
- alchemy/src/os/exec.ts
- alchemy/test/os/exec.test.ts
1. Enhanced `ExecProps.memoize` to support file-based memoization:
- Previously: `memoize?: boolean`
- Now: `memoize?: boolean | { patterns: string[] }`
- Patterns can be an array of file names or globs, relative to the given working directory if provided or `process.cwd()` otherwise (uses `glob` from `fs/promises`, compatible with Bun and Node.js >= 22)
2. Added tests verifying the new file pattern functionality:
- Commands are memoized when files haven't changed
- Commands are re-executed when files are modified
```typescript
const result = await Exec("build", {
command: "npm run build",
memoize: { patterns: ["src/**/*.ts", "package.json"] }
});
```
> feat(os): memoize exec from file patterns

- alchemy/src/cloudflare/d1-database.ts
- alchemy/test/cloudflare/d1-database.test.ts
There was a bug caused by GetDatabase not returning `primaryLocationHint` and our invalid-update detection assuming it did. This change uses the actual input properties instead.
> fix(cloudflare): allow D1 update read replication mode when primary location hint is explcitly set

- alchemy/src/cloudflare/wrangler.json.ts
Updates Vectorize bindings from `vectorize_indexes` to `vectorize` in `wrangler.json` to match Cloudflare's [current API](https://developers.cloudflare.com/workers/wrangler/configuration/#vectorize-indexes).
> fix(cloudflare): update vectorize_indexes to vectorize in wrangler.json.ts

- alchemy/src/cloudflare/vectorize-index.ts
- alchemy/src/cloudflare/vectorize-metadata-index.ts
- alchemy/src/context.ts
- alchemy/test/cloudflare/vectorize-index.test.ts
- alchemy/test/cloudflare/vectorize-metadata-index.test.ts
We recently changed the way symbols are used in a Resource's properties which has triggered no-op updates because it counts as the properties changing (it's a diff) https://github.com/sam-goodwin/alchemy/pull/177
This change updates the VectorizeIndex and VectorizeMetadataIndex which do not allow updates to check if the properties have actually changed so that these "no-op" updates can still flow through.
> fix(cloudflare): allow no-op update of vectorize index and metadata index

- alchemy/src/vercel/project.ts
Just discovered this bug.  Some settings cannot be updated on a Vercel Project after creation.
I missed this one in my testing:
```console
@packages/infra:build: Update:  "vercel/production/project"
@packages/infra:build: 62 |         if (!response.ok) {
@packages/infra:build: 63 |             let error = new Error(`API error: ${response.statusText}`, {
@packages/infra:build: 64 |                 cause: response,
@packages/infra:build: 65 |             });
@packages/infra:build: 66 |             try {
@packages/infra:build: 67 |                 error = Object.assign(new Error(response.statusText, { cause: response }), (await response.json())?.error);
@packages/infra:build:                                            ^
@packages/infra:build: error: Invalid request: should NOT have …
```
> fix: VercelProject 400 with gitRepository

- alchemy/src/cloudflare/analytics-engine.ts
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/src/util/assert-never.ts
- alchemy/test/cloudflare/worker.test.ts
Adds the ability to bind to cloudflare worker analytics engine datasets
https://developers.cloudflare.com/analytics/analytics-engine/
Odd kind of binding, since there is no iteraction with cloudflare's API.
- New datasets get created when they get used
- Old datasets die when the data in them gets 3 months old
- No ability to delete data or datasets
> Add cloudflare workers analytics engine binding

- alchemy/src/cloudflare/worker.ts
Ran into a bug where it was trying to upload event sources when deleting the worker
> fix(cloudflare): do not include eventSources when uploading stub worker during delete phase

- alchemy-web/docs/providers/cloudflare/worker.md
- alchemy/src/cloudflare/durable-object-namespace.ts
- alchemy/src/cloudflare/worker-metadata.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/test/cloudflare/worker.test.ts
- biome.json
Share durable objects between workers by defining them in one worker and accessing them from another:
```ts
import { Worker, DurableObjectNamespace } from "alchemy/cloudflare";
// Worker that defines and owns the durable object
const dataWorker = await Worker("data-worker", {
name: "data-worker",
entrypoint: "./src/data.ts",
bindings: {
// Bind to its own durable object
STORAGE: new DurableObjectNamespace("storage", {
className: "DataStorage"
})
}
});
// Worker that accesses the durable object from another worker
const apiWorker = await Worker("api-worker", {
name: "api-worker",
entrypoint: "./src/api.ts", 
bindings: {
// Cross-script binding to the data worker's durable object
SHARED_STORAGE: dataWorker.bindings.STORAGE
}
});
```
> feat(cloudflare): support binding to a DO hosted in another Worker

- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/worker-metadata.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/workflow.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/src/index.ts
- alchemy/src/type.ts
- alchemy/test/cloudflare/worker.test.ts
- examples/cloudflare-worker/alchemy.run.ts
- examples/cloudflare-worker/src/rpc.ts
- examples/cloudflare-worker/src/worker.ts
```ts
export const rpc = await Worker(`cloudflare-worker-rpc${BRANCH_PREFIX}`, {
entrypoint: "./src/rpc.ts",
rpc: MyRPC,
// or use a type alias if MyRPC can't be imported (e.g. it imports clouflare:workeres)
// rpc: type<MyRPC> 
});
export const worker = await Worker(`cloudflare-worker-worker${BRANCH_PREFIX}`, {
RPC: rpc,
},
});
````
> feat(cloudflare): Worker RPC binding types

- alchemy/package.json
- bun.lock
This isn't a complete fix yet but it at least improves the current experience. The crux of the issue is that `.d.ts` files aren't used by the compiler to produce the library outputs. As a result the generated `types.d.ts` file for CloudControl is not in the `lib` directory which breaks the typing and `any` gets used as a fallback.
This uses `cpx` to copy the file into the lib outputs so that the types will work as expected. However, this is not an ideal fix as there are still typing errors which fail silently. If you change the file from `types.d.ts` to `types.ts` you see these errors explicitly but doing so breaks compilation since these errors need to be resolved to compile.
I will follow up with a more complete fix.
> fix: include types.d.ts file in lib

- .github/workflows/test.yml
- alchemy-web/docs/concepts/state.md
- alchemy/src/fs/file-system-state-store.ts
- alchemy/test/aws/function.test.ts
- alchemy/test/cloudflare/bucket.test.ts
- alchemy/test/cloudflare/durable-object.test.ts
- biome.json
Perhaps you want to change the location of the `.alchemy` directory in a monorepo.
```typescript
const app = await alchemy("my-app", {
stateStore: (scope) => new FileSystemStateStore(scope, {
rootDir: path.resolve(import.meta.dir, "..", ".alchemy")
})
});
```
> feat(fs): allow overriding .alchemy dir

- alchemy-web/docs/providers/cloudflare/worker.md
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/worker-metadata.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/test/cloudflare/bucket.test.ts
- alchemy/test/cloudflare/worker.test.ts
Use `WorkerRef` to reference an existing worker by its service name rather than by resource instance. This is useful for worker-to-worker bindings when you need to reference a worker that already exists.
```ts
import { Worker, WorkerRef } from "alchemy/cloudflare";
const callerWorker = await Worker("caller", {
bindings: {
TARGET_WORKER: WorkerRef({
// reference the worker by name (not created with Alchemy)
service: "target-worker"
})
},
});
```
If you're using a WorkerEntrypoint RPC, you can provide its type:
```ts
import { Worker, WorkerRef } from "alchemy/cloudflare";
import type { MyWorkerEntrypoint } from "./src/worker.ts";
const callerWorker = await Worker("caller", {
name: "caller-worker",
bindings: {
TARGET_WORKER: WorkerRef<MyWorkerEntrypoint>({
service: "target-worker", …
```
> feat(cloudflare): support binding to an external worker by name

- alchemy-web/.vitepress/config.mts
- alchemy-web/docs/telemetry/index.md
- alchemy/package.json
- alchemy/src/alchemy.ts
- alchemy/src/apply.ts
- alchemy/src/cloudflare/auth.ts
- alchemy/src/cloudflare/website.ts
- alchemy/src/resource.ts
- alchemy/src/scope.ts
- alchemy/src/test/bun.ts
- alchemy/src/test/vitest.ts
- alchemy/src/util/telemetry/client.ts
- alchemy/src/util/telemetry/constants.ts
- alchemy/src/util/telemetry/context.ts
- alchemy/src/util/telemetry/index.ts
- alchemy/src/util/telemetry/types.ts
- alchemy/src/util/xdg-paths.ts
- alchemy/tsconfig.json
- alchemy/tsconfig.test.json
- package.json
- stacks/telemetry.run.ts
- Events: `app.start`, `app.success`, `app.error`, `resource.start`, `resource.success`, `resource.error`, `resource.skip`, `resource.read`
- Properties:
- elapsed time for `*.success` and `*.error` events
- resource name and status for `resource.*` events
- serialized error for `resource.error`
- Metadata (included in all events):
- anonymous user ID (stored in XDG config directory)
- anonymous project ID (uses root git commit hash for project)
- system info (e.g. OS, version, arch, CPU count, memory)
- runtime name and version (e.g. workerd, Bun 1.2.15, Node 22.15.0)
- CI provider if applicable (e.g. GitHub Actions)
- Alchemy version and phase
- Warning shown when anonymous user ID is generated for first time on system
- Opt out by setting `ALCHEMY_TELEMETRY_DISABLED` or …
> feat: anonymous telemetry with opt-out

- alchemy/src/index.ts
- alchemy/src/scope.ts
- alchemy/src/util/logger.ts
Use normal console if no scope is available
also export `logger` for users to use
> fix: fallback to console if no scope is available

- alchemy/src/apply.ts
- alchemy/src/destroy.ts
- alchemy/src/util/cli.ts
- bun.lock
Logging prefixes in `alchemy/src/apply.ts` and `alchemy/src/destroy.ts` were converted to lowercase for improved consistency and readability.
*   `SETUP` was changed to `setup`.
*   `SKIPPED` was changed to `skipped`.
*   `CREATING` and `UPDATING` were changed to `creating` and `updating` respectively.
*   `CREATED` and `UPDATED` were changed to `created` and `updated`.
*   `DELETING` was changed to `deleting` and its color updated to `redBright`.
*   `DELETED` was changed to `deleted`.
In `alchemy/src/util/cli.ts`, a `getTimestamp()` function was introduced to format the current time as `HH:MM:SS`. The `task` logger was updated to prepend this timestamp, colored gray, to all log messages. This aligns the logging output with common development tools like Vite, providing immediate temporal …
> feat: update logging format in cli.ts to match vite

- alchemy/src/cloudflare/do-state-store/internal.ts
- alchemy/src/cloudflare/do-state-store/store.ts
- alchemy/src/util/telemetry/client.ts
Before we can use the DOFS state store, we have to wait for DNS to update. We have retry logic already, but it wasn't aggressive enough, and also logged the whole response which was unnecessary.
Anyway, here's a fix.
> fix(cloudflare): 404 error when deploying dofs state store

- alchemy-web/docs/guides/cloudflare-worker.md
- alchemy-web/docs/providers/cloudflare/worker.md
- alchemy/src/cloudflare/api.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/util/safe-fetch.ts
- alchemy/test/cloudflare/fetch-utils.ts
- alchemy/test/cloudflare/worker.test.ts
Closes #350.
Deploy worker versions for testing and staging before promoting to production. Worker versions create isolated deployments with preview URLs that don't affect your live worker.
```ts
import { Worker } from "alchemy/cloudflare";
// Create a versioned worker for testing
const previewWorker = await Worker("my-worker", {
name: "my-worker",
entrypoint: "./src/worker.ts",
version: "pr-123", // Version label for display in the console
});
// Access the preview URL for testing
console.log(`Preview URL: ${previewWorker.url}`);
// Output: https://{version-hash}-my-worker.subdomain.workers.dev
```
> feat(cloudflare): add Worker version/preview support with labels

- alchemy/src/cloudflare/vite.ts
- alchemy/src/cloudflare/website.ts
- alchemy/src/cloudflare/worker-assets.ts
- alchemy/src/cloudflare/worker.ts
Websites were defaulting to not_found_handling: "single_page_application" which breaks SSR by default
> fix(cloudflare): configure Websites to support SSR by default

- alchemy-web/docs/guides/cloudflare-worker.md
- alchemy-web/docs/providers/cloudflare/worker.md
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/worker-stub.ts
- alchemy/test/cloudflare/worker-stub.test.ts
```ts
const workerA = await Worker("workerA", {
entrypoint: "index.ts",
name: "workerA",
bindings: {
workerB: await WorkerStub<MyWorker>("workerB", {
name: "workerB",
}),
},
});
const _workerB = await Worker("workerB", {
entrypoint: "index.ts",
name: "workerB",
bindings: {
workerA,
},
});
const env = workerA.Env;
const _string: string = await env.workerB.foo();
// @ts-expect-error
const _number: number = await env.workerB.foo();
// @ts-expect-error
env.workerB.bar();
```
> feat(cloudflare): support RPC type in WorkerStub

- alchemy/src/fs/file-system-state-store.ts
- alchemy/src/fs/file.ts
- doesn't call create folder if its trying to create `.`
- fixes a colon in file paths in FS-state-stire
> fix(fsss & fs): better support for windows file system

- alchemy-web/docs/guides/cloudflare-worker.md
- alchemy-web/docs/providers/cloudflare/custom-domain.md
- alchemy-web/docs/providers/cloudflare/worker.md
- alchemy/src/cloudflare/custom-domain.ts
- alchemy/src/cloudflare/route.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/zone.ts
- alchemy/src/util/safe-fetch.ts
- alchemy/test/cloudflare/custom-domain.test.ts
You can now configure `domains` on the `Worker` resource:
```ts
import { Worker } from "alchemy/cloudflare";
const worker = await Worker("api", {
name: "api-worker",
entrypoint: "./src/api.ts",
domains: ["api.example.com", "admin.example.com"],
});
```
It supports an `string | object`:
```ts
const worker = await Worker("api", {
name: "api-worker",
entrypoint: "./src/api.ts",
domains: [
{
domainName: "api.example.com",
zoneId: "YOUR_ZONE_ID", // Optional - will be inferred if not provided
adopt: true, // Adopt existing domain if it exists
},
"admin.example.com", // Zone ID will be inferred
],
});
```
The same change has been made for `routes`, opening it up to accept `string` for brevity.
```ts
const worker = await Worker("api", {
name: "api-worker",
entrypoint: "./src/api.ts",
routes: …
```
> feat(cloudflare): support Worker.domains for custom domains

- alchemy/src/cloudflare/worker/miniflare.ts
- alchemy/src/util/find-open-port.ts
- examples/cloudflare-worker-simple/alchemy.run.ts
Finds an open port starting at 1337 to use for Miniflare dev.
> fix(cloudflare): consistent ports for miniflare dev server

- alchemy/src/scope.ts
- alchemy/test/alchemy.test.ts
- alchemy/test/replace.test.ts
- added tests matching the corrupted state cause by the DOSS issue. https://github.com/sam-goodwin/alchemy/issues/585
- made sure that corrupted state is disposed of. sadly we do not have enough information to reliably destroy this because we cannot identify the handler
> feat(core): warning if pendingDeletions has corrupted resources

- bun.lock
- package.json
Biome 2 is stable now, so no need to keep using the beta.
> chore: update biome to 2.0.6

- alchemy/src/cloudflare/vectorize-index.ts
- alchemy/test/cloudflare/vectorize-index.test.ts
currently, alchemy fails to adopt existing vectorize index because cloudflare returns `vectorize.index.duplicate_name - Index name "<index-name>"` message which is missing the target _already exists_ keyword
> fix(cloudflare): update keyword for adopting an existing vectorize index

- alchemy/src/aws/account-id.ts
- alchemy/src/aws/bucket.ts
- alchemy/src/aws/function.ts
- alchemy/src/aws/oidc/oidc-provider.ts
- alchemy/src/aws/policy-attachment.ts
- alchemy/src/aws/policy.ts
- alchemy/src/aws/queue.ts
- alchemy/src/aws/role.ts
- alchemy/src/aws/s3-state-store.ts
- alchemy/src/aws/ses.ts
- alchemy/src/aws/ssm-parameter.ts
- alchemy/src/aws/table.ts
- examples/aws-app/.env.local
All Alchemy resources for AWS will use the `AWS_ENDPOINT`, if available, and pass it to the relevant AWS SDK clients.
> feat(aws): support aws endpoint environment variable

- .github/workflows/pr-preview.yml
- alchemy/src/cloudflare/container.ts
- alchemy/src/docker/api.ts
- alchemy/test/cloudflare/container.test.ts
Closes #654 (we now stream stdout/stderr of `docker build`)
Closes #660 (fixed the adoption bug that was only present when creating Container and binding to a Worker. Previously we'd only tested adoption working with ContainerApplication resource directly)
> fix(cloudflare): adopt Container when binding to a Worker

- alchemy-web/src/content/docs/guides/cloudflare-worker.mdx
- alchemy-web/src/content/docs/providers/cloudflare/worker.mdx
- alchemy/src/cloudflare/worker-metadata.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/test/cloudflare/test-helpers.ts
- alchemy/test/cloudflare/worker.test.ts
- alchemy/test/cloudflare/wrangler-json.test.ts
Set the maximum CPU time in milliseconds that the worker can use:
```ts
const worker = await Worker("api", {
name: "api-worker",
entrypoint: "./src/api.ts",
limits: {
cpu_ms: 300_000,
},
});
```
> feat(cloudflare): support cpu_ms limit on Worker

- alchemy/src/destroy.ts
- alchemy/test/replace.test.ts
- bun.lock
Replace had a bug where it would pass in the old resource state so `this.output.??` would refer to the new resource instead of the old resource.
> fix(core): replace should use old resource state when deleting

- alchemy-web/src/content/docs/concepts/resource.mdx
- alchemy-web/src/content/docs/concepts/scope.md
- alchemy/src/alchemy.ts
- alchemy/src/apply.ts
- alchemy/src/aws/s3-state-store.ts
- alchemy/src/destroy.ts
- alchemy/src/resource.ts
- alchemy/src/scope.ts
- alchemy/src/test/options.ts
- alchemy/src/util/safe-fetch.ts
- alchemy/test/cloudflare/pipeline.test.ts
- alchemy/test/cloudflare/rate-limit.test.ts
- alchemy/test/scope.test.ts
- bun.lock
By default, Alchemy will destroy scopes in a sequential order. You can configure the default behavior for the whole `alchemy` app, Scope (`alchemy.run`) or for a specific `Resource `:
```typescript
const app = await alchemy("my-app", {
destroyStrategy: "parallel"
});
await alchemy.run("my-app", {
destroyStrategy: "parallel"
}, async (scope) => {
// resources will be deleted in parallel during scope deletion/finalization
await Resource("resource1", {});
await Resource("resource2", {});
});
const Database = Resource(
"neon::Database",
{ destroyStrategy: "parallel" },
async function(this: Context<Database>, id: string, props: DatabaseProps): Promise<Database> {
if (this.phase === "delete") {
return this.destroy();
}
// these sub-resources will be deleted in parallel during the Database …
```
> feat(core): configure parallel delete on Scope and Provider

- alchemy-web/src/content/docs/providers/cloudflare/bucket.md
- alchemy/src/cloudflare/api-response.ts
- alchemy/src/cloudflare/bucket.ts
- alchemy/test/cloudflare/bucket.test.ts
- alchemy/test/cloudflare/pipeline.test.ts
- alchemy/test/runtime/app.ts
- alchemy/test/state/r2-rest-state-store.test.ts
- bun.lock
- examples/cloudflare-worker-bootstrap/index.ts
We currently use the S3-compatible API to empty an R2 bucket before deleting it. This PR switches to the REST API so you don't need to provide specialized credentials. Closes #723.
Also:
- Cleaned up some dead code
- We weren't returning the R2.dev subdomain if enabled, so I added that
- We had a function to set CORS rules but it wasn't being called anywhere - fixed that
> fix(cloudflare): don't require r2 access credentials to auto-empty bucket

- alchemy-web/src/content/docs/providers/random/random-string.md
- alchemy/package.json
- alchemy/src/random/index.ts
- alchemy/src/random/random-string.ts
- alchemy/test/random/random-string.test.ts
Generate a default random string (32 bytes, hex encoded):
```ts
import { RandomString } from "alchemy/random";
const apiKey = await RandomString("api-key");
// Result: 64 character hex string (e.g., "a1b2c3d4...")
```
Generate shorter random strings for verification codes:
```ts
import { RandomString } from "alchemy/random";
const verificationCode = await RandomString("email-verification", {
length: 8,
encoding: "hex"
});
// Result: 16 character hex string
```
> feat(random): add RandomString resource and alchemy/random export

- alchemy/src/cloudflare/worker-stub.ts
We log the status code but not the response body. This should fix that.
> fix(cloudflare): log error response on empty worker creation failure

- alchemy/src/cloudflare/assets.ts
Found a bug when using sylinks in an astro site. We were treating a symlinked directory as a file and breaking with "invalid read operation on directory" and also skipping assets.
> fix(cloudflare): handle symlink directories in Worker Assets

- alchemy-web/src/content/docs/providers/cloudflare/hyperdrive.md
- alchemy/src/cloudflare/hyperdrive.ts
- alchemy/src/cloudflare/miniflare/build-worker-options.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/src/secret.ts
- alchemy/test/cloudflare/hyperdrive.test.ts
Example usage:
```ts
const db = await Hyperdrive("my-postgres-db", {
name: "my-postgres-db",
origin: "postgresql://user:password@ep-example-host-1234.us-east-1.aws.neon.tech/mydb?sslmode=require",
dev: {
origin: "postgres://user:password@localhost:5432/postgres",
},
});
```
> feat(cloudflare): allow local connection string for hyperdrive

- alchemy/src/cloudflare/wrangler.json.ts
Our local asset handling doesn't match the remote behavior because we weren't writing the relevant configuration properties (`not-found_handling`, `html_handling`, and `run_worker_first`) to the generated `wrangler.jsonc`.
This fixes that to ensure parity.
Note: This is related to but not the same as #787. Seems like an Alchemy's behavior is the same as Wrangler with remote deployments — but our docs and examples aren't quite aligned with the expected behavior. We can update that in a separate PR.
> fix(cloudflare): correct wrangler.json assets config

- alchemy/src/cloudflare/website.ts
Closes #834.
The problem: if you set `compatibility: "node"` in a Website resource, this wouldn't be propagated to the `wrangler.jsonc`, causing Node.js imports like `node:async_hooks` to fail in development. Here's our fix.
> fix(cloudflare): propagate compatibility preset to wrangler.jsonc

- alchemy/src/cloudflare/website.ts
If a user set `NODE_ENV=production` in their `TanStackStart` website's `bindings`, then `alchemy dev` would pass it to `vite dev` which breaks the client side bundle.
When trying to resolve the RPC client for a `createServerFn`, for some reason the `process.env.TSS_APP_BASE` was still present in the client side bundle, which would then error with the following message:
```
ReferenceError: process is not defined
```
This change sets `NODE_ENV=development` when running the dev command for a website.
Question: should we set it `development` for all cases, or only when the user accidentally sets it as `production`? OR should we just fatal?
> fix(cloudflare): overwrite NODE_ENV when running vite dev

- alchemy/src/cloudflare/d1-migrations.ts
- alchemy/src/cloudflare/worker-bundle.ts
Right now we use fs.glob in two places where we should've used the `glob` package for compatibility with Node.js 20. This is a quick fix.
> fix(cloudflare): use glob instead of fs.glob for node 20 compatibility

- alchemy/bin/services/execute-alchemy.ts
When you Ctrl + C out of the CLI, sometimes it shows an error even when it's a clean exit. This handles that by rewriting exit code 130 to 0.
> fix(cli): ensure exit code 0 for sigint

- alchemy/src/cloudflare/miniflare/build-worker-options.ts
- alchemy/src/cloudflare/miniflare/miniflare-controller.ts
Updates our Miniflare controller to properly register Durable Objects in the Wrangler dev registry so the binding can be accessed from a website.
> fix(cloudflare): register durable object bindings for websites

- alchemy/src/resource.ts
We used to error if you tried to register a Resource with the same type name, e.g. `cloudflare::Worker`. Unfortunately, we also register each Resource on `globalThis` which means that if there are two instances of `alchemy` in your dependencies, it will fail.
It was originally assumed that proper peer dependencies would resolve this and that it was indicative of a user-side configuration error. But, we recently learned that in a PNPM monorepo, even if all the versions are aligned, PNPM will create different symlinks to the same package version.
From the perspective of Node/Bun/etc. a module's identity is its file path and it does not follow symlinks eagerly. So even in a perfectly aligned monorepo with all the same alchemy versions, there would still be duplicate instances. 
To support …
> fix(core): support multiple instances of alchemy in a monorepo environment

- alchemy/bin/services/github-workflow.ts
This changes our create template script to generate a github ci/cd workflow that installs the user's preferred package manager instead of assuming bun
> fix(cli): adapt CI workflows to the user's chosen package manager

- alchemy/src/cloudflare/sveltekit/plugin.ts
The svelte language server always runs from the root of the workspace.
So, if you have a Website in `apps/web`, for example, the `svelte.config.js` will be evaluated from the root of the project instead of `apps/web`.
However, `alchemy dev` will run within `apps/web` and the `alchemy()` svelte plugin assumes to be run within the right directory to discover the .alchemy folder.
For now, we work around this by just returning a no-op adapter. I don't think our plugin is needed for the svelte language server intellisense to work.
> fix(cloudflare): alchemy svelte plugin is a no-op when run within the svelte language server

- alchemy/src/cloudflare/react-router/react-router.ts
- alchemy/src/cloudflare/vite/vite.ts
React Router doesn't currently work in SPA mode because the `ReactRouter` resource always expects a server entrypoint. To fix this:
> fix(cloudflare): allow React Router apps to be deployed in SPA mode

- alchemy-web/public/robots.txt
Our website doesn't have a robots.txt, which may prevent LLMs from reading our docs.
> chore: add robots.txt to docs

- alchemy/src/cloudflare/astro/astro.ts
- alchemy/src/cloudflare/miniflare/paths.ts
Closes #860.
Uses `AsyncLocalStorage` to detect when Miniflare path validation calls should not cause an error to be thrown.
> fix(cloudflare): skip path validation during astro output type check

- alchemy/src/cloudflare/durable-object-namespace.ts
- alchemy/src/neon/project.ts
- alchemy/src/util/idempotent-spawn.ts
There was a bug with how we imported find-process that did not work in plain `node`, this adds some defensive checks to support `node`, `bun` and `tsx`
> fix(core): support importing find-process on plain node

- alchemy/src/util/dedent.ts
Noticed that our `dedent` tests weren't passing.
Before:
```
❯ alchemy/test/util/dedent.test.ts (8 tests | 3 failed) 8ms
✓ dedent > removes common indentation 5ms
× dedent > removes leading and trailing blank lines 5ms
→ expected '\n      line1\n      line2\n' to be 'line1\nline2' // Object.is equality
✓ dedent > preserves extra indentation 5ms
✓ dedent > handles empty template 5ms
✓ dedent > handles single line 5ms
✓ dedent > interpolates values correctly 1ms
× dedent > preserves blank lines in between 1ms
→ expected '      line1\n\n      line3' to be 'line1\n\nline3' // Object.is equality
× dedent > returns empty for only whitespace lines 1ms
→ expected '\n   ' to be '' // Object.is equality
```
After:
```
✓ alchemy/test/util/dedent.test.ts (8 tests) 2ms
✓ dedent > removes common …
```
> fix(core): pass dedent tests

- alchemy/src/cloudflare/worker-assets.ts
- Use `extractCloudflareResult` to improve error handling and logging for Workers asset uploads
- Use `withExponentialBackoff` to retry asset uploads on failure
> fix(cloudflare): improve asset upload error handling and add retries

- alchemy-web/astro.config.mjs
- alchemy-web/package.json
- alchemy-web/src/content/docs/advanced/serde.md
- alchemy-web/src/content/docs/blog/2025-07-01-how-alchemy-is-different.md
- alchemy-web/src/content/docs/concepts/state.mdx
- alchemy-web/src/content/docs/guides/cloudflare-state-store.mdx
- alchemy-web/src/content/docs/guides/planetscale-postgres.mdx
- alchemy-web/src/content/docs/providers/cloudflare/api-schema.md
- alchemy-web/src/content/docs/providers/cloudflare/email-address.md
- alchemy-web/src/content/docs/providers/cloudflare/email-catch-all.md
- alchemy-web/src/content/docs/providers/cloudflare/email-routing.md
- alchemy-web/src/content/docs/providers/cloudflare/email-rule.md
- alchemy-web/src/content/docs/providers/cloudflare/worker.mdx
- alchemy-web/src/content/docs/providers/docker/index.md
- alchemy-web/src/content/docs/what-is-alchemy.md
- bun.lock
A member in Discord reported a broken link in our docs. This PR:
- adds the [`starlight-links-validator`](https://github.com/HiDeoo/starlight-links-validator) plugin
- corrects all of the broken links that the validator identified
- cleans up unused dependencies and commented out code in `astro.config.mjs`
**Question:** I found some broken links to a "custom state store" guide. Was that guide removed?
> chore(docs): correct broken links and add validation

- alchemy-web/src/content/docs/guides/ci.mdx
The fix adds GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} to the deployment step. The GITHUB_TOKEN is automatically provided by GitHub Actions and has the necessary permissions.
Otherwise:
```
ERROR Scope failed api/pr-69/preview-comment
WARN Scope is in error, skipping finalize
ERROR Scope failed api/pr-69
node:internal/modules/run_main:123
triggerUncaughtException(
^
Error: GitHub repository not found
```
> Add GITHUB_TOKEN to CI guide

- alchemy/package.json
- alchemy/src/cloudflare/bundle/plugin-wasm.ts
- alchemy/test/cloudflare/bundle.test.ts
- alchemy/test/cloudflare/test-handlers/cojson-wasm.ts
- bun.lock
A user was unable to deploy a worker that imports from `cojson-core-wasm/edge-lite`. This was because the wasm file was located in a nested directory of the `cojson-core-wasm` package, so when we copy the WASM file into the bundle, we need to create the nested directory as part of the bundle output before attempting to copy the file.
> fix(cloudflare): wasm bundling fails when imported from nested directory

- alchemy/src/cloudflare/bucket.ts
- alchemy/src/cloudflare/index.ts
I forgot to export R2Object in #1016, so this PR fixes that. I also renamed a type in the bucket resource that conflicted with the R2Object resource. I’m unsure if this counts as a breaking change or if the new name is right.
> fix(cloudflare): add missing R2Object export

- alchemy/src/cloudflare/account-api-token.ts
- alchemy/src/cloudflare/permission-groups.ts
- alchemy/test/cloudflare/permission-groups.test.ts
`PermissionGroups` is a resource, but it should probably just be a function. It also doesn't log the full error message when there's a problem. Here's a quick fix.
> chore(cloudflare): make PermissionGroups a function & improve error handling

- alchemy-web/src/content/docs/providers/cloudflare/assets.md
- alchemy-web/src/content/docs/providers/cloudflare/nuxt.md
- alchemy-web/src/content/docs/providers/cloudflare/redwood.md
- alchemy-web/src/content/docs/providers/cloudflare/tanstack-start.md
- alchemy-web/src/content/docs/providers/cloudflare/vite.md
- alchemy-web/src/content/docs/providers/cloudflare/website.md
- alchemy/src/cloudflare/redwood/redwood.ts
- Removed references to Cloudflare Pages
- Corrected link to static assets page
- Removed preachy adjectives from TanStack and Vite description
> docs(cloudflare): correct static assets link and cf pages references

- alchemy-web/alchemy.run.ts
now managed by https://github.com/alchemy-run/telemetry
> chore(posthog): remove legacy posthog service

- alchemy/src/cloudflare/container.ts
| Instance Type  | vCPU | Memory (Min) | Memory (Max) |
|---------------|------|--------------|--------------|
| lite          | 1/16 | 256 MiB      | 2 GB         |
| basic         | 1/4  | 1 GiB        | 4 GB         |
| standard-1    | 1/2  | 4 GiB        | 8 GB         |
| standard-2    | 1    | 6 GiB        | 12 GB        |
| standard-3    | 2    | 8 GiB        | 16 GB        |
| standard-4    | 4    | 12 GiB       | 20 GB        |
> feat(cloudflare): add lite, standard-1,2,3,4 Container instance types

- alchemy/src/util/idempotent-spawn.ts
The TanStack Start dev server was getting stuck. Upon further inspection, I found that no logs were being recorded in our file. Running the vite dev server directly worked. Running within Alchemy without `idempotentSpawn` worked. So I kept removing things from `idempotentSpawn` until I narrowed it down to this.
I don't quite understand why this works but it does.
> fix: vite dev server hangs

- alchemy/src/cloudflare/bun-spa/bun-spa.ts
- examples/cloudflare-bun-spa/about.html
- examples/cloudflare-bun-spa/alchemy.run.ts
- examples/cloudflare-bun-spa/src/main.tsx
- examples/cloudflare-bun-spa/test/e2e.ts
dev w/tests output
```
DEV  Bun v1.2.22 ready in 7.56 ms
➜ http://localhost:3000/
Routes:
├── / → index.html
└── /about → about.html
{
url: "http://localhost:3000/",
apiUrl: "http://localhost:1338/",
}
Running Vite E2E test...
Bundled page in 24ms: index.html
Vite E2E test passed
Bundled page in 0ms: about.html
```
> feat(cloudflare): cloudflare-bun-spa resource now handles multiple frontend entrypoints
