- alchemy.config.ts
- alchemy/src/alchemize.ts
- alchemy/src/apply.ts
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/encrypt.ts
- alchemy/src/github/secret.ts
- alchemy/src/index.ts
- alchemy/src/input.ts
- alchemy/src/output.ts
- alchemy/src/secret.ts
- alchemy/src/serde.ts
- alchemy/src/state.ts
- examples/cloudflare-vite/alchemy.config.ts
- examples/cloudflare-vite/package.json
- examples/cloudflare-vite/src/auth/issuer.ts
- package.json
Example usage:
```ts
for (const [name, value] of Object.entries(githubSecrets)) {
if (value) {
new GitHubSecret(`github-secret-${name}`, {
owner: "sam-goodwin",
repository: "alchemy",
name,
value: secret(value),
});
}
}
alchemize({
stage: "github:alchemy",
mode: process.argv.includes("--destroy") ? "destroy" : "up",
// pass the password in (you can get it from anywhere, e.g. stdin)
password: process.env.SECRET_PASSPHRASE,
quiet: process.argv.includes("--verbose") ? false : true,
});
```
> feat: encrypted secret in state with password

- .cursorrules
- .github/workflows/test.yml
- alchemy.config.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/zone-settings.ts
- alchemy/src/cloudflare/zone.ts
- alchemy/test/cloudflare/zone.test.ts
```ts
const zone = await Zone("alchemy.run", {
name: "alchemy.run",
type: "full",
});
```
> feat: cloudflare Zone resource

- .github/workflows/test.yml
- alchemy-web/.vitepress/config.mts
- alchemy-web/docs/providers/fs/static-json-file.md
- alchemy.run.ts
- alchemy/package.json
- alchemy/src/cloudflare/account-api-token.ts
- alchemy/src/cloudflare/account-id.ts
- alchemy/src/cloudflare/api-error.ts
- alchemy/src/cloudflare/api.ts
- alchemy/src/cloudflare/auth.ts
- alchemy/src/cloudflare/bucket.ts
- alchemy/src/cloudflare/custom-domain.ts
- alchemy/src/cloudflare/dns-records.ts
- alchemy/src/cloudflare/kv-namespace.ts
- alchemy/src/cloudflare/permission-groups.ts
- alchemy/src/cloudflare/r2-rest-state-store.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/zone.ts
- alchemy/src/internal/docs/providers.ts
- bun.lock
Adds support for `wrangler login` OAuth login flow.
> [!CAUTION]
> OAuth login doesn't work for `AccountApiToken` or `PermissionGroups` resources.
> feat: support OAuth wrangler login

- alchemy-web/.vitepress/config.mts
- alchemy-web/docs/guides/cloudflare-durable-objects.md
- alchemy-web/docs/guides/cloudflare-vitejs.md
- alchemy-web/docs/guides/cloudflare-workflows.md
- alchemy-web/docs/guides/custom-resources.md
- alchemy-web/docs/guides/custom-state-store.md
- alchemy-web/docs/providers/cloudflare/durable-object-namespace.md
- alchemy-web/docs/providers/cloudflare/workflow.md
- alchemy/src/cloudflare/api-error.ts
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/durable-object-namespace.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/workflow.ts
- alchemy/src/internal/docs/providers.ts
- alchemy/test/cloudflare/worker.test.ts
```ts
const emailNotifier = new Workflow("EmailNotifier", {
// each of these are optional and default to `id`
// className: "EmailNotifier",
// workflowName: "EmailNotifier"
});
const worker = await Worker("Worker", {
name: "my-worker",
entrypoint: "./index.ts",
format: "esm",
bindings: {
EMAIL_NOTIFIER: emailNotifier,
},
});
```
> feat: cloudflare workflow

- alchemy/src/aws/table.ts
Dynamo sometimes throws 500s that were not being retried properly. I've seen this multiple times.
e.g. https://github.com/sam-goodwin/alchemy/actions/runs/14497684284/job/40670136625
This changes adds more defensive error handling.
> fix: harden retry logic of aws dynamodb table

- alchemy/src/cloudflare/api-error.ts
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/vectorize-index.ts
- alchemy/src/cloudflare/vectorize-metadata-index.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/src/test/bun.ts
- alchemy/test/cloudflare/d1-database.test.ts
- alchemy/test/cloudflare/vectorize-index.test.ts
- alchemy/test/cloudflare/vectorize-metadata-index.test.ts
```ts
const index = await VectorizeIndex("MyIndex", {
dimensions: 768,
metric: "cosine",
});
await VectorizeMetadataIndex(`Category`, {
index: vectorIndex,
propertyName: "category",
indexType: "string",
});
```
> feat: cloudflare vectorize index and metadata index

- .github/workflows/test.yml
- alchemy/src/aws/function.ts
- alchemy/src/cloudflare/api-error.ts
- alchemy/test/aws/function.test.ts
- alchemy/test/aws/role.test.ts
- alchemy/test/handler.ts
- scripts/test.sh
The Lambda Function URL was not configured properly, this change inokes the create function url command
> fix: lambda function url

- .github/workflows/test.yml
- alchemy.run.ts
- alchemy/src/github/index.ts
- alchemy/src/github/repository-environment.ts
- alchemy/src/github/secret.ts
- alchemy/test/github/repository-environment.test.ts
- alchemy/test/github/secret.test.ts
- bun.lock
```ts
const testEnvironment = await RepositoryEnvironment("GithubTestEnvironment", {
owner: "sam-goodwin",
repository: "alchemy",
name: "test",
reviewers: {
users: ["sam-goodwin"],
},
});
await GitHubSecret(`OPENAI_API_KEY`, {
owner: "sam-goodwin",
repository: "alchemy",
value: alchemy.secret(process.env.OPENAI_API_KEY)
environment: testEnvironment.name,
})
```
> feat: github repository environment and secrets

- alchemy-web/docs/providers/aws/function.md
- alchemy/src/aws/function.ts
- alchemy/test/aws/function.test.ts
- Added support for setting `invokeMode` for aws function url. 
- default to `BUFFERED`
> Feature add invokemode to aws function

- alchemy/src/cloudflare/tanstack-start.ts
- alchemy/src/cloudflare/website.ts
- bun.lock
- examples/cloudflare-tanstack-start/alchemy.run.ts
- examples/cloudflare-tanstack-start/package.json
- examples/cloudflare-tanstack-start/src/env.d.ts
- examples/cloudflare-tanstack-start/src/index.ts
- examples/cloudflare-tanstack-start/src/routes/api/users.$id.ts
- examples/cloudflare-tanstack-start/tsconfig.json
- tsconfig.json
The `Website` resource wasn't respecting `main`
> fix: respect 'main' property in Website

- alchemy-web/docs/providers/cloudflare/worker.md
- alchemy/src/cloudflare/worker.ts
- alchemy/test/cloudflare/worker.test.ts
the api replaces the cron defs wholesale on PUT so if there's manually defined triggers in the dash they'll be cleared, but that works for me at least :)
> feat(cloudflare): Worker cron schedules

- .cursor/rules/cloudflare.mdc
- .github/workflows/test.yml
- alchemy/package.json
- alchemy/src/cloudflare/ai-gateway.ts
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/hyperdrive.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/neon/api-error.ts
- alchemy/src/neon/api.ts
- alchemy/src/neon/index.ts
- alchemy/src/neon/project.ts
- alchemy/test/cloudflare/hyperdrive.test.ts
- alchemy/test/neon/project.test.ts
- stacks/env.ts
- stacks/repo.run.ts
```ts
const project = await NeonProject("project");
const hyperdrive = await Hyperdrive("hyperdrive", {
origin: project.connection_uris[0].connection_parameters,
});
export const website = await TanStackStart("tanstack-website", {
bindings: {
DB: hyperdrive,
},
});
import { env } from "cloudflare:workers";
env.DB.connect()
```
> feat: Cloudflare Hyperdrive & Neon Project

- alchemy-web/docs/guides/cloudflare-durable-objects.md
- alchemy-web/docs/guides/cloudflare-nuxt-pipeline.md
- alchemy-web/docs/guides/cloudflare-redwood.md
- alchemy-web/docs/guides/cloudflare-tanstack-start.md
- alchemy-web/docs/guides/cloudflare-vitejs.md
- alchemy-web/docs/guides/cloudflare-workflows.md
- alchemy-web/docs/guides/custom-resources.md
- alchemy/src/cloudflare/d1-database.ts
- alchemy/src/cloudflare/worker.ts
```ts
// this is now possible
const db = await D1Database("uptime-monitor-local")
// instead of redundant:
// const db = await D1Database("uptime-monitor-local", {
//   name: "uptime-monitor-local"
// })
```
> feat: default Worker and D1 names to id

- alchemy/src/cloudflare/r2-rest-state-store.ts
> fix: parse list response properly in r2 rest state store 

- alchemy-web/docs/what-is-alchemy.md
Auto-complete found it for me, so I didn't even notice until I read the docs again.
> Fix reference to R2(Rest)StateStore

- alchemy/package.json
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/browser-rendering.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/test/cloudflare/browser-handler.ts
- alchemy/test/cloudflare/browser-rendering.test.ts
- bun.lock
```ts
await Worker("my-worker", {
entrypoint: path.join(import.meta.dirname, "browser-handler.ts"),
format: "esm",
compatibilityFlags: ["nodejs_compat"], // Required for puppeteer
url: true, // Enable workers.dev URL to test the worker
bindings: {
MYBROWSER: new BrowserRendering(),
BROWSER_KV_DEMO: kvNamespace,
},
bundle: {
platform: "node", // required for puppeteer
},
});
```
> feat(cloudflare): BrowserRendering

- alchemy/src/cloudflare/zone.ts
Support disabling deletion of a CF zone:
```ts
await Zone("..", {
// default true
delete: false
});
> feat(cloudflare): support disabling deletion of Cloudflare Zone

- alchemy-web/docs/providers/cloudflare/zone.md
Update Cloudflare Zone Docs to match Alchemy 0.12.15
> Update Cloudflare Zone Docs

- alchemy/src/cloudflare/ai.ts
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/test/cloudflare/ai.test.ts
- alchemy/test/cloudflare/wrangler-json.test.ts
```ts
await Worker("my-worker, {
bindings: {
MYAI: new Ai(),
},
});
```
> feat(cloudflare): Ai binding

- alchemy/src/neon/project.ts
Neon [supports Postgres 17](https://neon.tech/blog/postgres-17)
> chore: neon now supports pg 17, make 16 default 

- alchemy/src/scope.ts
- scripts/smoke.sh
Closes https://github.com/sam-goodwin/alchemy/issues/135
> fix: propagate state store to nested scopes

- alchemy/src/cloudflare/r2-rest-state-store.ts
Closes https://github.com/sam-goodwin/alchemy/issues/135
> fix(cloudflare): use / as delimiter when listing in r2 rest state store

- alchemy/src/cloudflare/api.ts
- alchemy/src/cloudflare/user.ts
Closes https://github.com/sam-goodwin/alchemy/issues/140
> fix: support resolving account ID for account access token

- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/src/serde.ts
- alchemy/test/cloudflare/worker.test.ts
- alchemy/test/serde.test.ts
> feat(cloudflare): allow binding a Worker to itself

- alchemy/src/cloudflare/worker.ts
- alchemy/test/neon/project.test.ts
- examples/cloudflare-worker/alchemy.run.ts
- examples/cloudflare-worker/src/do.ts
- examples/cloudflare-worker/src/worker.ts
- examples/cloudflare-worker/src/workflow.ts
Workflows should not have class migrations
> fix(cloudflare): do not apply new_class_migration to a Workflow

- alchemy-web/docs/providers/cloudflare/route.md
- alchemy-web/docs/providers/cloudflare/worker.md
- alchemy-web/package.json
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/route.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/internal/docs/providers.ts
- alchemy/test/cloudflare/route.test.ts
- bun.lock
```ts
const zone = await Zone("..")
const worker = await Worker("..", { .. });
await Route("route", {
pattern: "sub.domain.com/route/*,
script: worker,
zoneId: zone.id,
})
```
> feat(cloudflare): Route resource

- alchemy/src/aws/function.ts
Expose layers option for Lambda functions
> feat(aws): support lambda layers in Function

- alchemy/src/scope.ts
- alchemy/test/scope.test.ts
- alchemy/test/upstash/redis.test.ts
Simple issue with order of operations.
> fix: scope.phase is undefined when initializing stateStore 

- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/kv-namespace.ts
- alchemy/src/cloudflare/worker.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/test/cloudflare/pipeline.test.ts
```ts
await Worker("foo", {
bindings: {
MY_NAMESPACE: {
type: "kv_namespace",
id: "uuid..."
}
}
});
```
> feat(cloudflare): allow binding to a KV namespace by UUID

- alchemy-web/docs/providers/sentry/client-key.md
- alchemy-web/docs/providers/sentry/project.md
- alchemy-web/docs/providers/sentry/team.md
- alchemy/package.json
- alchemy/src/sentry/api.ts
- alchemy/src/sentry/client-key.ts
- alchemy/src/sentry/index.ts
- alchemy/src/sentry/project.ts
- alchemy/src/sentry/team.ts
- alchemy/test/neon/project.test.ts
- alchemy/test/sentry/client-key.test.ts
- alchemy/test/sentry/project.test.ts
- alchemy/test/sentry/team.test.ts
This was largely done by AI, TDD, and usage in my own project using these docs:
- https://docs.sentry.io/api/projects/
- https://docs.sentry.io/api/teams/
1. Get `SENTRY_AUT_TOKEN` from https://sentry.io/settings/account/api/auth-tokens/ and make one with scopes like:
> alerts:read, alerts:write, event:admin, event:read, event:write, member:admin, member:invite, member:read, member:write, org:admin, org:integrations, org:read, org:write, project:admin, project:read, project:releases, project:write, team:admin, team:read, team:write
1. Get `SENTRY_ORG` from https://sentry.io/settings/organization/
Update `.env` with the following:
```ini
SENTRY_AUTH_TOKEN=sntryu_...
SENTRY_ORG=replace_with_your_org
```
```sh
bun test alchemy/test/sentry
```
You should see:
```console
bun test v1.0.29 …
```
> feat: Vibing alchemy/sentry

- alchemy/src/cloudflare/website.ts
- Add support for using cwd when running script
- Better check through all the possible options for props.wrangler when building filename and path for temporary wrangler file
- Added compatibility_flags for temporary wrangler if avail in the props, to avoid vite complaining when doing the build
> FIX for cwd/wrangler.props

- alchemy/src/vercel/project.ts
- alchemy/test/vercel/project-domain.test.ts
- alchemy/test/vercel/project.test.ts
It was mistakenly removed in #169 due to a lint error (that didn't appear in #202?)
> fix: Re-introduce #202 with biome-ignore

- .github/workflows/pkg-pr.yml
- alchemy/package.json
setup pkg.pr.new for relasing PRs as installable packages for testing
>[!IMPORTANT]
> Install the github app before merging <https://github.com/apps/pkg-pr-new>
> chore: setup pkg-pr workflow

- alchemy/package.json
To reproduce the issue, revert this change and run
```
bun install
bun test:smoke
```
> reorder the stupid exports

- .github/workflows/claude-auto-review.yml
A new GitHub Actions workflow, `.github/workflows/claude-auto-review.yml`, was created to automate pull request reviews using Claude.
Key features of the new workflow:
*   **Automatic Triggering**: Runs on `pull_request` `opened` and `synchronize` events, eliminating the need for manual `@claude` mentions.
*   **Bot Protection**: Includes a conditional check (`if: github.actor != 'dependabot[bot]'
> chore: Set up claude auto-review configuration

- alchemy-web/astro.config.mjs
- alchemy-web/src/components/Hero.astro
- alchemy-web/src/content/docs/index.md
- alchemy-web/src/content/docs/index.mdx
This overrides Starlight's default Hero component and adds a similar experience to what's on the current site. This isn't _complete_ and the design can certainly be improved, but it has everything we need to build on.
> Add basic hero to Astro site

- README.md
Allows users to use DeepWiki to ask questions about the codebase
> Update README.md with DeepWiki

- alchemy/src/cloudflare/worker.ts
Closes https://github.com/sam-goodwin/alchemy/issues/539
> fix(cloudflare): adopt inner CustomDomain and Route if Worker.adopt

- .gitignore
- alchemy/bin/constants.ts
- alchemy/bin/services/package-manager.ts
- alchemy/templates/astro/_env
- alchemy/templates/typescript/_env
- alchemy/templates/typescript/_env.example
- alchemy/templates/vite/_env
- alchemy/test/create.test.ts
- bun.lock
- package.json
Also made it so the smoke test runs against the repo version, not NPM version of alchemy
> fix(cloudflare): include .env in astro, typescript and astro project templates

- alchemy/src/docker/api.ts
- alchemy/src/docker/image.ts
Closes https://github.com/sam-goodwin/alchemy/issues/560
> fix(docker): race condition in authorizing to docker registry

- alchemy-web/src/content/docs/providers/cloudflare/nuxt.md
- alchemy-web/src/content/docs/providers/cloudflare/redwood.md
- alchemy-web/src/content/docs/providers/cloudflare/tanstack-start.md
- alchemy-web/src/content/docs/providers/cloudflare/vite.md
- alchemy-web/src/content/docs/providers/cloudflare/website.md
- alchemy-web/src/content/docs/providers/cloudflare/worker.mdx
- alchemy-web/src/content/docs/providers/cloudflare/wrangler.json.md
- alchemy/src/cloudflare/website.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/test/cloudflare/website.test.ts
```ts
await Website("website", {
transform: {
wrangler: (spec) => ({
...spec,
main: "new/main.ts"
})
});
```
> feat(cloudflare): add transform?: { wrangler } hook to WranglerJson resource

- alchemy/src/cloudflare/do-state-store/store.ts
- alchemy/test/replace.test.ts
fixes: https://github.com/sam-goodwin/alchemy/issues/585
> fix(doss): do not working with replace

- alchemy/src/cloudflare/bundle/nodejs-import-warning-plugin.ts
- alchemy/test/cloudflare/nodejs-import-warning.test.ts
Problem persisted even after #586. Forgive me for the harm I have caused this world. But it's fixed now, or at least it works on my machine™️.
> test(cloudflare): node.js import warning test failure

- alchemy-web/src/content/docs/providers/cloudflare/container.md
- alchemy/src/cloudflare/container.ts
- alchemy/src/cloudflare/worker.ts
- examples/cloudflare-container/alchemy.run.ts
- examples/cloudflare-worker-simple/alchemy.run.ts
```ts
const container = await Container<MyContainer>("container", {
name: `${app.name}-container-${app.stage}`,
className: "MyContainer",
adopt: true,
});
```
> feat(cloudflare): Container.adopt

- alchemy/src/cloudflare/worker.ts
- alchemy/test/cloudflare/queue.test.ts
Closes https://github.com/sam-goodwin/alchemy/issues/645
> fix(cloudflare): adopt Worker with Queue event source

- alchemy-web/alchemy.run.ts
- alchemy/src/cloudflare/zone.ts
```ts
await Zone("my.com", {
alwaysUseHttps: "off" // default "on"
})
```
> fix(cloudflare): zones force alwaysUseHttps

- alchemy/src/cloudflare/d1-migrations.ts
This runs and records the migration in a single request. Closes #692.
Not as good as a transaction, but perhaps the next best thing — at least it's not possible for one request to run while the other fails.
> fix(cloudflare): improve atomicity of d1 migrations

- alchemy-web/src/content/docs/concepts/cli.mdx
- alchemy/bin/commands/deploy.ts
- alchemy/bin/commands/dev.ts
- alchemy/bin/services/execute-alchemy.ts
- alchemy/src/alchemy.ts
- alchemy/src/apply.ts
- alchemy/src/scope.ts
- alchemy/src/test/bun.ts
- alchemy/src/test/options.ts
- alchemy/src/test/vitest.ts
- alchemy/test/scope.test.ts
```sh
alchemy deploy --force
bun ./alchemy.run.ts --force
```
```ts
await alchemy("my-app", {
force: true
});
alchemy.run("my-scope", { force: true }, async () => {
//..
});
```
> feat(core): force updates

- alchemy/src/cloudflare/zone.ts
Otherwise we don't find our zone.
The PR branch fixed issue for us :+1: thanks StackBlitz
> fetch all zones in findZoneForHostname

- .github/workflows/pkg-pr.yml
- scripts/generate-pnpm-workspace.yaml.ts
Only issue i could find is https://github.com/stackblitz-labs/pkg.pr.new/issues/204
Not sure if this will work with bun though ...
> chore: resolve catalog dependencies in pkg.pr.new

- alchemy-web/src/content/docs/providers/cloudflare/ruleset.md
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/rule.ts
- alchemy/src/cloudflare/ruleset.ts
- alchemy/test/cloudflare/ruleset.test.ts
> [!CAUTION]
> A Ruleset will overwrite the entire entrypoint ruleset for the specified phase. All existing rules in that phase will be replaced with the rules you provide.
Create custom firewall rules to block malicious traffic and challenge suspicious requests.
```ts
const firewall = await Ruleset("custom-firewall", {
zone: "example.com",
phase: "http_request_firewall_custom",
rules: [
{
description: "Block bad IPs",
expression: "ip.src in {1.2.3.4 1.2.3.5}",
action: "block"
},
{
description: "Challenge suspicious requests",
expression: "cf.threat_score > 50",
action: "challenge"
}
]
});
```
Configure sophisticated rate limiting with multiple characteristics and custom timeouts.
```ts
const advancedRateLimit = await Ruleset("advanced-rate-limit", {
zone: "example.com",
phase: …
```
> feat(cloudflare): WAF Ruleset resource

- alchemy/src/cloudflare/assets.ts
- alchemy/src/cloudflare/worker-bundle.ts
was working with astro and ran into issues where the filepaths had windows separators and that doesn't work well with cloudflare's upload
> fix(cloudflare): fix worker asset and no-bundle filepaths on windows

- alchemy/bin/services/github-workflow.ts
The `alchemy` CLI will pass in these and `alchemy()` will detect them automatically. We should not encourage this anti-pattern of process.env.STAGE or process.env.BRANCH_PREFIX
If the user selected "yes" to github CI workflows we would generate the following bad code:
```ts
const stage = process.env.STAGE || process.env.BRANCH_PREFIX;
const app = await alchemy("my-app", {
stage
});
```
Now we generate:
```ts
const app = await alchemy("my-app");
```
And set `--stage` in the github workflow:
```yml
- name: Deploy Preview
run: bun run deploy --stage pr-\${{ github.event.pull_request.number }}
```
> fix(cli): templates should not modify the alchemy app stage

- alchemy-web/src/content/docs/providers/cloudflare/bucket.md
- alchemy/src/cloudflare/bucket.ts
- alchemy/test/cloudflare/bucket.test.ts
- bun.lock
- package.json
- vitest.setup.ts
> feat(cloudflare): r2 bucket lifecycle and lock rules

- alchemy-web/public/robots.txt
- alchemy/src/cloudflare/astro/astro.ts
- bun.lock
The `Website` resource defaults to `spa: true` and is not overridden by the `Astro` resource. This may cause Astro websites to mistakenly be interpreted as single-page apps.
> fix(cloudflare): set `spa: false` for astro resource

- alchemy/src/cloudflare/hyperdrive.ts
- alchemy/test/cloudflare/hyperdrive.test.ts
Enable the `adopt` option for Hyperdrive if the `name` conflicts.
> feat(cloudflare): adopt hyperdrive

- alchemy/src/util/memoize.ts
The `CloudflareStateStore` was found to update multiple times in a single deploy when the `forceUpdate` option was enabled.
The underlying cause is that although the function for updating the store is memoized, the cache key used for memoization was non-deterministic. This is because the `stateToken` is a `Secret`, so the `name` property may differ even if the value is the same. Since the store is initialized separately for each scope, this means each scope results in a separate update call. For example:
```ts
const app = await alchemy("alchemy:state", {
stateStore: (scope) =>
new CloudflareStateStore(scope, {
stateToken: alchemy.secret("1234567890"), // secret is reinstantiated for every scope with a different name (e.g. `anonymous-secret-0`, `anonymous-secret-1`, etc
forceUpdate: true, …
```
> fix(core): deterministic cache keys for function memoization

- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/test/cloudflare/wrangler-json.test.ts
should fix: https://github.com/sam-goodwin/alchemy/issues/933
> fix(cloudflare): fix support for producer only queue bindings for wranglerjson

- alchemy/src/util/idempotent-spawn.ts
fixes #911
long term scope.spawn should probably be farmed out to something we can listen to via our debug server (since its realistically just mirroring `console.log` and `console.error` so CDP works fine or we can have an entire different set of messages for it if we want)
> fix(core): commands run by scope.spawn are properly mirrored to stdio

- alchemy-web/src/content/docs/providers/cloudflare/hyperdrive.md
- alchemy/src/cloudflare/bindings.ts
- alchemy/src/cloudflare/bound.ts
- alchemy/src/cloudflare/hyperdrive-ref.ts
- alchemy/src/cloudflare/index.ts
- alchemy/src/cloudflare/miniflare/build-worker-options.ts
- alchemy/src/cloudflare/wrangler.json.ts
- alchemy/test/cloudflare/hyperdrive-ref.test.ts
```ts
// refer to one by its UUID
await HyperdriveRef({
id: "asd83q1asd...",
});
```
```ts
// refer to one by its name (we will look it up using API)
await HyperdriveRef({
name: "by-name",
});
```
> feat(cloudflare): HyperdriveRef

- alchemy-web/src/content/docs/providers/cloudflare/bucket.md
- alchemy/src/cloudflare/api.ts
- alchemy/src/cloudflare/bucket.ts
- alchemy/src/state/r2-rest-state-store.ts
- alchemy/test/cloudflare/bucket.test.ts
- alchemy/test/util.ts
```ts
const bucket = await R2Bucket(..)
const obj = await bucket.get("key");
await bucket.put("key", value)
await bucket.delete("key")
```
> feat(cloudflare): add head, get, list, put and delete methods to R2Bucket

- alchemy/src/neon/branch.ts
- alchemy/src/neon/project.ts
Related to https://github.com/sam-goodwin/alchemy/pull/1003
> fix(neon): remove this(..) syntax

- examples/cloudflare-container/alchemy.run.ts
- examples/cloudflare-container/e2e.ts
- examples/cloudflare-container/src/worker.ts
- examples/cloudflare-container/tsconfig.json
The container test wasn't passing because it was making a request to the container on the wrong port.
> chore(examples): fix cloudflare container and add e2e test
